-- Migration: 001_initial_scriptura
-- Description: Initial schema for Bible books and verses tables.
-- Run with: psql -h HOST -U USER DBNAME -f 001_initial_scriptura.sql

-- Books catalog (canonical Latin data only)
CREATE TABLE books (
    id              INTEGER PRIMARY KEY,
    latin_abbr      TEXT NOT NULL UNIQUE,
    latin_name      TEXT NOT NULL,
    is_deuterocanonical BOOLEAN NOT NULL DEFAULT FALSE
);

-- Book name translations
CREATE TABLE book_names (
    book_id     INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    language    TEXT NOT NULL,
    name        TEXT NOT NULL,
    PRIMARY KEY (book_id, language)
);

-- Individual verses (Latin Vulgate text or any OSIS source)
CREATE TABLE verses (
    verse_id    INTEGER PRIMARY KEY,
    book_id     INTEGER NOT NULL REFERENCES books(id),
    chapter     INTEGER NOT NULL,
    verse       INTEGER NOT NULL,
    text        TEXT NOT NULL,
    UNIQUE(book_id, chapter, verse)
);

CREATE INDEX idx_verses_book_chapter ON verses(book_id, chapter);
CREATE INDEX idx_verses_verse_id ON verses(verse_id);

-- Seed the books table (73 books)
INSERT INTO books (id, latin_abbr, latin_name, is_deuterocanonical) VALUES
-- Protestant canon (1-66)
(1,  'Gen',   'Genesis',             FALSE),
(2,  'Exod',  'Exodus',              FALSE),
(3,  'Lev',   'Leviticus',           FALSE),
(4,  'Num',   'Numeri',              FALSE),
(5,  'Deut',  'Deuteronomium',       FALSE),
(6,  'Jos',   'Josue',               FALSE),
(7,  'Jdgs',  'Judices',             FALSE),
(8,  'Ruth',  'Ruth',                FALSE),
(9,  '1Sam',  'I Samuel',            FALSE),
(10, '2Sam',  'II Samuel',           FALSE),
(11, '1Reg',  'III Regum',           FALSE),
(12, '2Reg',  'IV Regum',            FALSE),
(13, '1Par',  'I Paralipomenon',    FALSE),
(14, '2Par',  'II Paralipomenon',    FALSE),
(15, 'Esd',   'Esdrae',              FALSE),
(16, 'Neh',   'Nehemias',            FALSE),
(17, 'Est',   'Esther',              FALSE),
(18, 'Job',   'Job',                 FALSE),
(19, 'Ps',    'Psalmi',              FALSE),
(20, 'Prov',  'Proverbia',           FALSE),
(21, 'Eccl',  'Ecclesiastes',        FALSE),
(22, 'Cant',  'Canticum Canticorum', FALSE),
(23, 'Isa',   'Isaias',              FALSE),
(24, 'Jer',   'Jeremias',            FALSE),
(25, 'Lam',   'Lamentationes',       FALSE),
(26, 'Ezek',  'Ezechielis',          FALSE),
(27, 'Dan',   'Daniel',              FALSE),
(28, 'Hos',   'Osee',                FALSE),
(29, 'Joel',  'Joel',                FALSE),
(30, 'Am',    'Amos',                FALSE),
(31, 'Abd',   'Abdias',              FALSE),
(32, 'Jon',   'Jonas',               FALSE),
(33, 'Mich',  'Michaeas',            FALSE),
(34, 'Nah',   'Nahum',               FALSE),
(35, 'Hab',   'Abacuc',             FALSE),
(36, 'Sph',   'Sophonias',           FALSE),
(37, 'Agg',   'Aggaeus',             FALSE),
(38, 'Zach',  'Zacharias',           FALSE),
(39, 'Mal',   'Malachias',           FALSE),
(40, 'Matt',  'Matthaeus',           FALSE),
(41, 'Mc',    'Marcus',              FALSE),
(42, 'Lc',    'Lucas',               FALSE),
(43, 'Io',    'Joannes',             FALSE),
(44, 'Act',   'Actus',               FALSE),
(45, 'Rom',   'Romanos',             FALSE),
(46, '1Cor',  'I Corinthios',        FALSE),
(47, '2Cor',  'II Corinthios',       FALSE),
(48, 'Gal',   'Galatas',             FALSE),
(49, 'Eph',   'Ephesios',            FALSE),
(50, 'Phil',  'Philippenses',        FALSE),
(51, 'Col',   'Colossenses',         FALSE),
(52, '1Th',   'I Thessalonicenses',  FALSE),
(53, '2Th',   'II Thessalonicenses', FALSE),
(54, '1Tim',  'I Timotheum',         FALSE),
(55, '2Tim',  'II Timotheum',        FALSE),
(56, 'Tit',   'Ad Titum',            FALSE),
(57, 'Phlm',  'Ad Philemonem',       FALSE),
(58, 'Heb',   'Ad Hebraeos',         FALSE),
(59, 'Jac',   'Jacobi',              FALSE),
(60, '1Pet',  'I Petri',             FALSE),
(61, '2Pet',  'II Petri',            FALSE),
(62, '1Io',   'I Joannis',           FALSE),
(63, '2Io',   'II Joannis',         FALSE),
(64, '3Io',   'III Joannis',         FALSE),
(65, 'Jud',   'Judae',               FALSE),
(66, 'Apoc',  'Apocalypsis',         FALSE),
-- Deuterocanonical (67-73)
(67, 'Tob',   'Tobias',              TRUE),
(68, 'Jdt',   'Judith',              TRUE),
(69, 'Sap',   'Sapientia',           TRUE),
(70, 'Eccli', 'Ecclesiasticus',      TRUE),
(71, 'Bar',   'Baruch',              TRUE),
(72, '1Mach', 'I Machabaeorum',      TRUE),
(73, '2Mach', 'II Machabaeorum',     TRUE);

-- Seed book name translations
-- Latin is already in books.latin_name; this table stores translated names.
-- Language codes follow IANA BCP 47 / ISO 639-1 (la, en, es, pl, cs, da, de, fr, it, hu, nl, pt, uk, vi, ja, ko, zh)
INSERT INTO book_names (book_id, language, name) VALUES

-- ===== English =====
(1,  'en', 'Genesis'),
(2,  'en', 'Exodus'),
(3,  'en', 'Leviticus'),
(4,  'en', 'Numbers'),
(5,  'en', 'Deuteronomy'),
(6,  'en', 'Joshua'),
(7,  'en', 'Judges'),
(8,  'en', 'Ruth'),
(9,  'en', '1 Samuel'),
(10, 'en', '2 Samuel'),
(11, 'en', '1 Kings'),
(12, 'en', '2 Kings'),
(13, 'en', '1 Chronicles'),
(14, 'en', '2 Chronicles'),
(15, 'en', 'Ezra'),
(16, 'en', 'Nehemiah'),
(17, 'en', 'Esther'),
(18, 'en', 'Job'),
(19, 'en', 'Psalms'),
(20, 'en', 'Proverbs'),
(21, 'en', 'Ecclesiastes'),
(22, 'en', 'Song of Songs'),
(23, 'en', 'Isaiah'),
(24, 'en', 'Jeremiah'),
(25, 'en', 'Lamentations'),
(26, 'en', 'Ezekiel'),
(27, 'en', 'Daniel'),
(28, 'en', 'Hosea'),
(29, 'en', 'Joel'),
(30, 'en', 'Amos'),
(31, 'en', 'Obadiah'),
(32, 'en', 'Jonah'),
(33, 'en', 'Micah'),
(34, 'en', 'Nahum'),
(35, 'en', 'Habakkuk'),
(36, 'en', 'Zephaniah'),
(37, 'en', 'Haggai'),
(38, 'en', 'Zechariah'),
(39, 'en', 'Malachi'),
(40, 'en', 'Matthew'),
(41, 'en', 'Mark'),
(42, 'en', 'Luke'),
(43, 'en', 'John'),
(44, 'en', 'Acts'),
(45, 'en', 'Romans'),
(46, 'en', '1 Corinthians'),
(47, 'en', '2 Corinthians'),
(48, 'en', 'Galatians'),
(49, 'en', 'Ephesians'),
(50, 'en', 'Philippians'),
(51, 'en', 'Colossians'),
(52, 'en', '1 Thessalonians'),
(53, 'en', '2 Thessalonians'),
(54, 'en', '1 Timothy'),
(55, 'en', '2 Timothy'),
(56, 'en', 'Titus'),
(57, 'en', 'Philemon'),
(58, 'en', 'Hebrews'),
(59, 'en', 'James'),
(60, 'en', '1 Peter'),
(61, 'en', '2 Peter'),
(62, 'en', '1 John'),
(63, 'en', '2 John'),
(64, 'en', '3 John'),
(65, 'en', 'Jude'),
(66, 'en', 'Revelation'),
(67, 'en', 'Tobit'),
(68, 'en', 'Judith'),
(69, 'en', 'Wisdom'),
(70, 'en', 'Sirach'),
(71, 'en', 'Baruch'),
(72, 'en', '1 Maccabees'),
(73, 'en', '2 Maccabees'),

-- ===== Spanish =====
(1,  'es', 'Génesis'),
(2,  'es', 'Éxodo'),
(3,  'es', 'Levítico'),
(4,  'es', 'Números'),
(5,  'es', 'Deuteronomio'),
(6,  'es', 'Josué'),
(7,  'es', 'Jueces'),
(8,  'es', 'Rut'),
(9,  'es', '1 Samuel'),
(10, 'es', '2 Samuel'),
(11, 'es', '1 Reyes'),
(12, 'es', '2 Reyes'),
(13, 'es', '1 Crónicas'),
(14, 'es', '2 Crónicas'),
(15, 'es', 'Esdras'),
(16, 'es', 'Nehemías'),
(17, 'es', 'Ester'),
(18, 'es', 'Job'),
(19, 'es', 'Salmos'),
(20, 'es', 'Proverbios'),
(21, 'es', 'Eclesiastés'),
(22, 'es', 'Cantares'),
(23, 'es', 'Isaías'),
(24, 'es', 'Jeremías'),
(25, 'es', 'Lamentaciones'),
(26, 'es', 'Ezequiel'),
(27, 'es', 'Daniel'),
(28, 'es', 'Oseas'),
(29, 'es', 'Joel'),
(30, 'es', 'Amós'),
(31, 'es', 'Abdías'),
(32, 'es', 'Jonás'),
(33, 'es', 'Miqueas'),
(34, 'es', 'Nahúm'),
(35, 'es', 'Habacuc'),
(36, 'es', 'Sofonías'),
(37, 'es', 'Ageo'),
(38, 'es', 'Zacarías'),
(39, 'es', 'Malaquías'),
(40, 'es', 'Mateo'),
(41, 'es', 'Marcos'),
(42, 'es', 'Lucas'),
(43, 'es', 'Juan'),
(44, 'es', 'Hechos'),
(45, 'es', 'Romanos'),
(46, 'es', '1 Corintios'),
(47, 'es', '2 Corintios'),
(48, 'es', 'Gálatas'),
(49, 'es', 'Efesios'),
(50, 'es', 'Filipenses'),
(51, 'es', 'Colosenses'),
(52, 'es', '1 Tesalonicenses'),
(53, 'es', '2 Tesalonicenses'),
(54, 'es', '1 Timoteo'),
(55, 'es', '2 Timoteo'),
(56, 'es', 'Tito'),
(57, 'es', 'Filemón'),
(58, 'es', 'Hebreos'),
(59, 'es', 'Santiago'),
(60, 'es', '1 Pedro'),
(61, 'es', '2 Pedro'),
(62, 'es', '1 Juan'),
(63, 'es', '2 Juan'),
(64, 'es', '3 Juan'),
(65, 'es', 'Judas'),
(66, 'es', 'Apocalipsis'),
(67, 'es', 'Tobías'),
(68, 'es', 'Judit'),
(69, 'es', 'Sabiduría'),
(70, 'es', 'Sirácida'),
(71, 'es', 'Baruc'),
(72, 'es', '1 Macabeos'),
(73, 'es', '2 Macabeos'),

-- ===== Polish =====
(1,  'pl', 'Księga Rodzaju'),
(2,  'pl', 'Księga Wyjścia'),
(3,  'pl', 'Księga Kapłańska'),
(4,  'pl', 'Księga Liczb'),
(5,  'pl', 'Księga Powtórzonego Prawa'),
(6,  'pl', 'Księga Jozuego'),
(7,  'pl', 'Księga Sędziów'),
(8,  'pl', 'Księga Rut'),
(9,  'pl', 'Pierwsza Księga Samuela'),
(10, 'pl', 'Druga Księga Samuela'),
(11, 'pl', 'Pierwsza Księga Królewska'),
(12, 'pl', 'Druga Księga Królewska'),
(13, 'pl', 'Pierwsza Księga Kronik'),
(14, 'pl', 'Druga Księga Kronik'),
(15, 'pl', 'Księga Ezdrasza'),
(16, 'pl', 'Księga Nehemiasza'),
(17, 'pl', 'Księga Estery'),
(18, 'pl', 'Księga Hioba'),
(19, 'pl', 'Księga Psalmów'),
(20, 'pl', 'Księga Przysłów'),
(21, 'pl', 'Księga Koheleta'),
(22, 'pl', 'Pieśń nad Pieśniami'),
(23, 'pl', 'Księga Izajasza'),
(24, 'pl', 'Księga Jeremiasza'),
(25, 'pl', 'Treny'),
(26, 'pl', 'Księga Ezechiela'),
(27, 'pl', 'Księga Daniela'),
(28, 'pl', 'Księga Ozeasza'),
(29, 'pl', 'Księga Joela'),
(30, 'pl', 'Księga Amosa'),
(31, 'pl', 'Księga Abdiasza'),
(32, 'pl', 'Księga Jonasza'),
(33, 'pl', 'Księga Micheasza'),
(34, 'pl', 'Księga Nahuma'),
(35, 'pl', 'Księga Habakuka'),
(36, 'pl', 'Księga Sofoniasza'),
(37, 'pl', 'Księga Aggeusza'),
(38, 'pl', 'Księga Zachariasza'),
(39, 'pl', 'Księga Malachiasza'),
(40, 'pl', 'Ewangelia według Mateusza'),
(41, 'pl', 'Ewangelia według Marka'),
(42, 'pl', 'Ewangelia według Łukasza'),
(43, 'pl', 'Ewangelia według Jana'),
(44, 'pl', 'Dzieje Apostolskie'),
(45, 'pl', 'List do Rzymian'),
(46, 'pl', 'Pierwszy List do Koryntian'),
(47, 'pl', 'Drugi List do Koryntian'),
(48, 'pl', 'List do Galatów'),
(49, 'pl', 'List do Efzjan'),
(50, 'pl', 'List do Filipian'),
(51, 'pl', 'List do Kolosan'),
(52, 'pl', 'Pierwszy List do Tesaloniczan'),
(53, 'pl', 'Drugi List do Tesaloniczan'),
(54, 'pl', 'Pierwszy List do Tymoteusza'),
(55, 'pl', 'Drugi List do Tymoteusza'),
(56, 'pl', 'List do Tytusa'),
(57, 'pl', 'List do Filemona'),
(58, 'pl', 'List do Hebrajczyków'),
(59, 'pl', 'List Jakuba'),
(60, 'pl', 'Pierwszy List Piotra'),
(61, 'pl', 'Drugi List Piotra'),
(62, 'pl', 'Pierwszy List Jana'),
(63, 'pl', 'Drugi List Jana'),
(64, 'pl', 'Trzeci List Jana'),
(65, 'pl', 'List Judy'),
(66, 'pl', 'Księga Apokalipsy'),
(67, 'pl', 'Księga Tobiasza'),
(68, 'pl', 'Księga Judyty'),
(69, 'pl', 'Księga Mądrości'),
(70, 'pl', 'Księga Syracha'),
(71, 'pl', 'Księga Barucha'),
(72, 'pl', 'Pierwsza Księga Machabejska'),
(73, 'pl', 'Druga Księga Machabejska'),

-- ===== Czech (Čeština) =====
(1,  'cs', 'Genesis'),
(2,  'cs', 'Exodus'),
(3,  'cs', 'Leviticus'),
(4,  'cs', 'Numeri'),
(5,  'cs', 'Deuteronomium'),
(6,  'cs', 'Jozue'),
(7,  'cs', 'Soudců'),
(8,  'cs', 'Rút'),
(9,  'cs', '1 Samuelova'),
(10, 'cs', '2 Samuelova'),
(11, 'cs', '1 Královská'),
(12, 'cs', '2 Královská'),
(13, 'cs', '1 Paralipomenon'),
(14, 'cs', '2 Paralipomenon'),
(15, 'cs', 'Ezdráš'),
(16, 'cs', 'Nehemiáš'),
(17, 'cs', 'Estér'),
(18, 'cs', 'Jób'),
(19, 'cs', 'Žalmy'),
(20, 'cs', 'Přísloví'),
(21, 'cs', 'Kazatel'),
(22, 'cs', 'Píseň písní'),
(23, 'cs', 'Izaiáš'),
(24, 'cs', 'Jeremiáš'),
(25, 'cs', 'Pláč'),
(26, 'cs', 'Ezechiel'),
(27, 'cs', 'Daniel'),
(28, 'cs', 'Ozeáš'),
(29, 'cs', 'Jóel'),
(30, 'cs', 'Amos'),
(31, 'cs', 'Abdiáš'),
(32, 'cs', 'Jonáš'),
(33, 'cs', 'Micheáš'),
(34, 'cs', 'Nahum'),
(35, 'cs', 'Abakuk'),
(36, 'cs', 'Sofoniáš'),
(37, 'cs', 'Aggeus'),
(38, 'cs', 'Zachariáš'),
(39, 'cs', 'Malachiáš'),
(40, 'cs', 'Matouš'),
(41, 'cs', 'Marek'),
(42, 'cs', 'Lukáš'),
(43, 'cs', 'Jan'),
(44, 'cs', 'Skutky'),
(45, 'cs', 'Římanům'),
(46, 'cs', '1 Korintským'),
(47, 'cs', '2 Korintským'),
(48, 'cs', 'Galatským'),
(49, 'cs', 'Efeským'),
(50, 'cs', 'Filipským'),
(51, 'cs', 'Koloským'),
(52, 'cs', '1 Tesalonickým'),
(53, 'cs', '2 Tesalonickým'),
(54, 'cs', '1 Timoteovi'),
(55, 'cs', '2 Timoteovi'),
(56, 'cs', 'Titovi'),
(57, 'cs', 'Filemonovi'),
(58, 'cs', 'Židům'),
(59, 'cs', 'Jakubův'),
(60, 'cs', '1 Petrův'),
(61, 'cs', '2 Petrův'),
(62, 'cs', '1 Janův'),
(63, 'cs', '2 Janův'),
(64, 'cs', '3 Janův'),
(65, 'cs', 'Judův'),
(66, 'cs', 'Zjevení Janovo'),
(67, 'cs', 'Tobit'),
(68, 'cs', 'Judit'),
(69, 'cs', 'Moudrost'),
(70, 'cs', 'Sírachovec'),
(71, 'cs', 'Baruch'),
(72, 'cs', '1 Makabejská'),
(73, 'cs', '2 Makabejská'),

-- ===== Danish (Dansk) =====
(1,  'da', 'Første Mosebog'),
(2,  'da', 'Anden Mosebog'),
(3,  'da', 'Tredje Mosebog'),
(4,  'da', 'Fjerde Mosebog'),
(5,  'da', 'Femte Mosebog'),
(6,  'da', 'Josva'),
(7,  'da', 'Dommerne'),
(8,  'da', 'Ruth'),
(9,  'da', 'Første Samuelsbog'),
(10, 'da', 'Anden Samuelsbog'),
(11, 'da', 'Første Kongerbog'),
(12, 'da', 'Anden Kongerbog'),
(13, 'da', 'Første Krønikebog'),
(14, 'da', 'Anden Krønikebog'),
(15, 'da', 'Ezra'),
(16, 'da', 'Nehemias'),
(17, 'da', 'Esther'),
(18, 'da', 'Job'),
(19, 'da', 'Salmernes Bog'),
(20, 'da', 'Ordsprogenes Bog'),
(21, 'da', 'Prædikerens Bog'),
(22, 'da', 'Højsangen'),
(23, 'da', 'Esajas'),
(24, 'da', 'Jeremias'),
(25, 'da', 'Klagesangene'),
(26, 'da', 'Ezekiels Bog'),
(27, 'da', ' Daniels Bog'),
(28, 'da', 'Hoseas'),
(29, 'da', 'Joel'),
(30, 'da', 'Amos'),
(31, 'da', 'Obadias'),
(32, 'da', 'Jonas'),
(33, 'da', 'Mikeas'),
(34, 'da', 'Nahum'),
(35, 'da', 'Habakkuk'),
(36, 'da', 'Sefanias'),
(37, 'da', 'Haggai'),
(38, 'da', 'Zakarias'),
(39, 'da', 'Malakias'),
(40, 'da', 'Matthæus'),
(41, 'da', 'Markus'),
(42, 'da', 'Lukas'),
(43, 'da', 'Johannes'),
(44, 'da', 'Apostlenes Gerninger'),
(45, 'da', 'Romerne'),
(46, 'da', 'Første Korintherbrev'),
(47, 'da', 'Andet Korintherbrev'),
(48, 'da', 'Galaterne'),
(49, 'da', 'Efeserne'),
(50, 'da', 'Filipperne'),
(51, 'da', 'Kolosserne'),
(52, 'da', 'Første Thessalonikerbrev'),
(53, 'da', 'Andet Thessalonikerbrev'),
(54, 'da', 'Første Timotheusbrev'),
(55, 'da', 'Andet Timotheusbrev'),
(56, 'da', 'Titus'),
(57, 'da', 'Filemon'),
(58, 'da', 'Hebræerne'),
(59, 'da', 'Jakobsbrevet'),
(60, 'da', 'Første Petersbrev'),
(61, 'da', 'Andet Petersbrev'),
(62, 'da', 'Første Johannesbrev'),
(63, 'da', 'Andet Johannesbrev'),
(64, 'da', 'Tredje Johannesbrev'),
(65, 'da', 'Judasbrevet'),
(66, 'da', 'Johannes'' Åbenbaring'),
(67, 'da', 'Tobit'),
(68, 'da', 'Judit'),
(69, 'da', 'Visdom'),
(70, 'da', 'Sirak'),
(71, 'da', 'Baruk'),
(72, 'da', 'Første Makkabæerbog'),
(73, 'da', 'Andet Makkabæerbog'),

-- ===== German (Deutsch) =====
(1,  'de', 'Genesis'),
(2,  'de', 'Exodus'),
(3,  'de', 'Leviticus'),
(4,  'de', 'Numeri'),
(5,  'de', 'Deuteronomium'),
(6,  'de', 'Josua'),
(7,  'de', 'Richter'),
(8,  'de', 'Rut'),
(9,  'de', '1. Samuel'),
(10, 'de', '2. Samuel'),
(11, 'de', '1. Könige'),
(12, 'de', '2. Könige'),
(13, 'de', '1. Chronik'),
(14, 'de', '2. Chronik'),
(15, 'de', 'Esra'),
(16, 'de', 'Nehemia'),
(17, 'de', 'Ester'),
(18, 'de', 'Hiob'),
(19, 'de', 'Psalmen'),
(20, 'de', 'Sprüche'),
(21, 'de', 'Prediger'),
(22, 'de', 'Hoheslied'),
(23, 'de', 'Jesaja'),
(24, 'de', 'Jeremia'),
(25, 'de', 'Klagelieder'),
(26, 'de', 'Hesekiel'),
(27, 'de', 'Daniel'),
(28, 'de', 'Hosea'),
(29, 'de', 'Joel'),
(30, 'de', 'Amos'),
(31, 'de', 'Obadja'),
(32, 'de', 'Jona'),
(33, 'de', 'Micha'),
(34, 'de', 'Nahum'),
(35, 'de', 'Habakuk'),
(36, 'de', 'Zefanja'),
(37, 'de', 'Haggai'),
(38, 'de', 'Sacharja'),
(39, 'de', 'Maleachi'),
(40, 'de', 'Matthäus'),
(41, 'de', 'Markus'),
(42, 'de', 'Lukas'),
(43, 'de', 'Johannes'),
(44, 'de', 'Apostelgeschichte'),
(45, 'de', 'Römer'),
(46, 'de', '1. Korinther'),
(47, 'de', '2. Korinther'),
(48, 'de', 'Galater'),
(49, 'de', 'Epheser'),
(50, 'de', 'Philipper'),
(51, 'de', 'Kolosser'),
(52, 'de', '1. Thessalonicher'),
(53, 'de', '2. Thessalonicher'),
(54, 'de', '1. Timotheus'),
(55, 'de', '2. Timotheus'),
(56, 'de', 'Titus'),
(57, 'de', 'Philemon'),
(58, 'de', 'Hebräer'),
(59, 'de', 'Jakobus'),
(60, 'de', '1. Petrus'),
(61, 'de', '2. Petrus'),
(62, 'de', '1. Johannes'),
(63, 'de', '2. Johannes'),
(64, 'de', '3. Johannes'),
(65, 'de', 'Judas'),
(66, 'de', 'Offenbarung'),
(67, 'de', 'Tobit'),
(68, 'de', 'Judit'),
(69, 'de', 'Weisheit'),
(70, 'de', 'Sirach'),
(71, 'de', 'Baruch'),
(72, 'de', '1. Makkabäer'),
(73, 'de', '2. Makkabäer'),

-- ===== French (Français) =====
(1,  'fr', 'Genèse'),
(2,  'fr', 'Exode'),
(3,  'fr', 'Lévitique'),
(4,  'fr', 'Nombres'),
(5,  'fr', 'Deutéronome'),
(6,  'fr', 'Josué'),
(7,  'fr', 'Juges'),
(8,  'fr', 'Ruth'),
(9,  'fr', '1 Samuel'),
(10, 'fr', '2 Samuel'),
(11, 'fr', '1 Rois'),
(12, 'fr', '2 Rois'),
(13, 'fr', '1 Chroniques'),
(14, 'fr', '2 Chroniques'),
(15, 'fr', 'Esdras'),
(16, 'fr', 'Néhémie'),
(17, 'fr', 'Esther'),
(18, 'fr', 'Job'),
(19, 'fr', 'Psaumes'),
(20, 'fr', 'Proverbes'),
(21, 'fr', 'Ecclésiaste'),
(22, 'fr', 'Cantique des Cantiques'),
(23, 'fr', 'Isaïe'),
(24, 'fr', 'Jérémie'),
(25, 'fr', 'Lamentations'),
(26, 'fr', 'Ézéchiel'),
(27, 'fr', 'Daniel'),
(28, 'fr', 'Osée'),
(29, 'fr', 'Joël'),
(30, 'fr', 'Amos'),
(31, 'fr', 'Abdias'),
(32, 'fr', 'Jonas'),
(33, 'fr', 'Michée'),
(34, 'fr', 'Nahum'),
(35, 'fr', 'Habacuc'),
(36, 'fr', 'Sophonie'),
(37, 'fr', 'Aggée'),
(38, 'fr', 'Zacharie'),
(39, 'fr', 'Malachie'),
(40, 'fr', 'Matthieu'),
(41, 'fr', 'Marc'),
(42, 'fr', 'Luc'),
(43, 'fr', 'Jean'),
(44, 'fr', 'Actes'),
(45, 'fr', 'Romains'),
(46, 'fr', '1 Corinthiens'),
(47, 'fr', '2 Corinthiens'),
(48, 'fr', 'Galates'),
(49, 'fr', 'Éphésiens'),
(50, 'fr', 'Philippiens'),
(51, 'fr', 'Colossiens'),
(52, 'fr', '1 Thessaloniciens'),
(53, 'fr', '2 Thessaloniciens'),
(54, 'fr', '1 Timothée'),
(55, 'fr', '2 Timothée'),
(56, 'fr', 'Tite'),
(57, 'fr', 'Philémon'),
(58, 'fr', 'Hébreux'),
(59, 'fr', 'Jacques'),
(60, 'fr', '1 Pierre'),
(61, 'fr', '2 Pierre'),
(62, 'fr', '1 Jean'),
(63, 'fr', '2 Jean'),
(64, 'fr', '3 Jean'),
(65, 'fr', 'Jude'),
(66, 'fr', 'Apocalypse'),
(67, 'fr', 'Tobit'),
(68, 'fr', 'Judith'),
(69, 'fr', 'Sagesse'),
(70, 'fr', 'Siracide'),
(71, 'fr', 'Baruch'),
(72, 'fr', '1 Maccabées'),
(73, 'fr', '2 Maccabées'),

-- ===== Italian (Italiano) =====
(1,  'it', 'Genesi'),
(2,  'it', 'Esodo'),
(3,  'it', 'Levitico'),
(4,  'it', 'Numeri'),
(5,  'it', 'Deuteronomio'),
(6,  'it', 'Giosuè'),
(7,  'it', 'Giudici'),
(8,  'it', 'Ruth'),
(9,  'it', '1 Samuele'),
(10, 'it', '2 Samuele'),
(11, 'it', '1 Re'),
(12, 'it', '2 Re'),
(13, 'it', '1 Cronache'),
(14, 'it', '2 Cronache'),
(15, 'it', 'Esdra'),
(16, 'it', 'Neemia'),
(17, 'it', 'Ester'),
(18, 'it', 'Giobbe'),
(19, 'it', 'Salmi'),
(20, 'it', 'Proverbi'),
(21, 'it', 'Qoelet'),
(22, 'it', 'Cantico dei Cantici'),
(23, 'it', 'Isaia'),
(24, 'it', 'Geremia'),
(25, 'it', 'Lamentazioni'),
(26, 'it', 'Ezechiele'),
(27, 'it', 'Daniele'),
(28, 'it', 'Osea'),
(29, 'it', 'Gioele'),
(30, 'it', 'Amos'),
(31, 'it', 'Abdia'),
(32, 'it', 'Giona'),
(33, 'it', 'Michea'),
(34, 'it', 'Nahum'),
(35, 'it', 'Abacuc'),
(36, 'it', 'Sofonia'),
(37, 'it', 'Aggeo'),
(38, 'it', 'Zaccaria'),
(39, 'it', 'Malachia'),
(40, 'it', 'Matteo'),
(41, 'it', 'Marco'),
(42, 'it', 'Luca'),
(43, 'it', 'Giovanni'),
(44, 'it', 'Atti degli Apostoli'),
(45, 'it', 'Romani'),
(46, 'it', '1 Corinzi'),
(47, 'it', '2 Corinzi'),
(48, 'it', 'Galati'),
(49, 'it', 'Efesini'),
(50, 'it', 'Filippesi'),
(51, 'it', 'Colossesi'),
(52, 'it', '1 Tessalonicesi'),
(53, 'it', '2 Tessalonicesi'),
(54, 'it', '1 Timoteo'),
(55, 'it', '2 Timoteo'),
(56, 'it', 'Tito'),
(57, 'it', 'Filemone'),
(58, 'it', 'Ebrei'),
(59, 'it', 'Giacomo'),
(60, 'it', '1 Pietro'),
(61, 'it', '2 Pietro'),
(62, 'it', '1 Giovanni'),
(63, 'it', '2 Giovanni'),
(64, 'it', '3 Giovanni'),
(65, 'it', 'Giuda'),
(66, 'it', 'Apocalisse'),
(67, 'it', 'Tobia'),
(68, 'it', 'Giuditta'),
(69, 'it', 'Sapienza'),
(70, 'it', 'Siracide'),
(71, 'it', 'Baruch'),
(72, 'it', '1 Maccabei'),
(73, 'it', '2 Maccabei'),

-- ===== Hungarian (Magyar) =====
(1,  'hu', 'Mózes 1. könyve'),
(2,  'hu', 'Mózes 2. könyve'),
(3,  'hu', 'Mózes 3. könyve'),
(4,  'hu', 'Mózes 4. könyve'),
(5,  'hu', 'Mózes 5. könyve'),
(6,  'hu', 'Józsua'),
(7,  'hu', 'Bírák'),
(8,  'hu', 'Rut'),
(9,  'hu', 'Sámuel 1. könyve'),
(10, 'hu', 'Sámuel 2. könyve'),
(11, 'hu', 'Királyok 1. könyve'),
(12, 'hu', 'Királyok 2. könyve'),
(13, 'hu', 'Krónikák 1. könyve'),
(14, 'hu', 'Krónikák 2. könyve'),
(15, 'hu', 'Ezdrás'),
(16, 'hu', 'Nehémiás'),
(17, 'hu', 'Eszter'),
(18, 'hu', 'Jób'),
(19, 'hu', 'Zsoltárok'),
(20, 'hu', 'Példabeszédek'),
(21, 'hu', 'Prédikátor'),
(22, 'hu', 'Énekek éneke'),
(23, 'hu', 'Ézsaiás'),
(24, 'hu', 'Jeremiás'),
(25, 'hu', 'Siralmak'),
(26, 'hu', 'Ezékiel'),
(27, 'hu', 'Dániel'),
(28, 'hu', 'Hósea'),
(29, 'hu', 'Jóel'),
(30, 'hu', 'Ámos'),
(31, 'hu', 'Abdiás'),
(32, 'hu', 'Jónás'),
(33, 'hu', 'Mikeás'),
(34, 'hu', 'Náhum'),
(35, 'hu', 'Habakuk'),
(36, 'hu', 'Zofoniás'),
(37, 'hu', 'Haggai'),
(38, 'hu', 'Zakariás'),
(39, 'hu', 'Malakiás'),
(40, 'hu', 'Máté'),
(41, 'hu', 'Márk'),
(42, 'hu', 'Lukács'),
(43, 'hu', 'János'),
(44, 'hu', 'Apostolok cselekedetei'),
(45, 'hu', 'Rómaiak'),
(46, 'hu', '1 Korintusiak'),
(47, 'hu', '2 Korintusiak'),
(48, 'hu', 'Galaták'),
(49, 'hu', 'Efézusiak'),
(50, 'hu', 'Filippiek'),
(51, 'hu', 'Kolosszeiek'),
(52, 'hu', '1 Thesszalonikiek'),
(53, 'hu', '2 Thesszalonikiek'),
(54, 'hu', '1 Timóteus'),
(55, 'hu', '2 Timóteus'),
(56, 'hu', 'Titusz'),
(57, 'hu', 'Filemon'),
(58, 'hu', 'Zsidók'),
(59, 'hu', 'Jakab'),
(60, 'hu', '1 Péter'),
(61, 'hu', '2 Péter'),
(62, 'hu', '1 János'),
(63, 'hu', '2 János'),
(64, 'hu', '3 János'),
(65, 'hu', 'Júdás'),
(66, 'hu', 'Jelenések'),
(67, 'hu', 'Tóbiás'),
(68, 'hu', 'Judit'),
(69, 'hu', 'Bölcsesség'),
(70, 'hu', 'Sirák'),
(71, 'hu', 'Baruch'),
(72, 'hu', '1 Makkabeus'),
(73, 'hu', '2 Makkabeus'),

-- ===== Dutch (Nederlands) =====
(1,  'nl', 'Genesis'),
(2,  'nl', 'Exodus'),
(3,  'nl', 'Leviticus'),
(4,  'nl', 'Numeri'),
(5,  'nl', 'Deuteronomium'),
(6,  'nl', 'Jozua'),
(7,  'nl', 'Richteren'),
(8,  'nl', 'Ruth'),
(9,  'nl', '1 Samuel'),
(10, 'nl', '2 Samuel'),
(11, 'nl', '1 Koningen'),
(12, 'nl', '2 Koningen'),
(13, 'nl', '1 Kronieken'),
(14, 'nl', '2 Kronieken'),
(15, 'nl', 'Ezra'),
(16, 'nl', 'Nehemia'),
(17, 'nl', 'Ester'),
(18, 'nl', 'Job'),
(19, 'nl', 'Psalmen'),
(20, 'nl', 'Spreuken'),
(21, 'nl', 'Prediker'),
(22, 'nl', 'Hooglied'),
(23, 'nl', 'Jesaja'),
(24, 'nl', 'Jeremia'),
(25, 'nl', 'Klaagliederen'),
(26, 'nl', 'Ezechiël'),
(27, 'nl', 'Daniël'),
(28, 'nl', 'Hosea'),
(29, 'nl', 'Joël'),
(30, 'nl', 'Amos'),
(31, 'nl', 'Obadja'),
(32, 'nl', 'Jona'),
(33, 'nl', ' Micha'),
(34, 'nl', 'Nahum'),
(35, 'nl', 'Habakuk'),
(36, 'nl', 'Zefanja'),
(37, 'nl', 'Haggai'),
(38, 'nl', 'Zacharia'),
(39, 'nl', 'Maleachi'),
(40, 'nl', 'Mattheüs'),
(41, 'nl', 'Marcus'),
(42, 'nl', 'Lukas'),
(43, 'nl', 'Johannes'),
(44, 'nl', 'Handelingen'),
(45, 'nl', 'Romeinen'),
(46, 'nl', '1 Korinthiërs'),
(47, 'nl', '2 Korinthiërs'),
(48, 'nl', 'Galaten'),
(49, 'nl', 'Efeziërs'),
(50, 'nl', 'Filippenzen'),
(51, 'nl', 'Kolossenzen'),
(52, 'nl', '1 Thessalonicenzen'),
(53, 'nl', '2 Thessalonicenzen'),
(54, 'nl', '1 Timotheüs'),
(55, 'nl', '2 Timotheüs'),
(56, 'nl', 'Titus'),
(57, 'nl', 'Filemon'),
(58, 'nl', 'Hebreeën'),
(59, 'nl', 'Jakobus'),
(60, 'nl', '1 Petrus'),
(61, 'nl', '2 Petrus'),
(62, 'nl', '1 Johannes'),
(63, 'nl', '2 Johannes'),
(64, 'nl', '3 Johannes'),
(65, 'nl', 'Judas'),
(66, 'nl', 'Openbaring'),
(67, 'nl', 'Tobit'),
(68, 'nl', 'Judit'),
(69, 'nl', 'Wijsheid'),
(70, 'nl', 'Sirach'),
(71, 'nl', 'Baruch'),
(72, 'nl', '1 Makkabeeën'),
(73, 'nl', '2 Makkabeeën'),

-- ===== Portuguese (Português) =====
(1,  'pt', 'Gênesis'),
(2,  'pt', 'Êxodo'),
(3,  'pt', 'Levítico'),
(4,  'pt', 'Números'),
(5,  'pt', 'Deuteronômio'),
(6,  'pt', 'Josué'),
(7,  'pt', 'Juízes'),
(8,  'pt', 'Rute'),
(9,  'pt', '1 Samuel'),
(10, 'pt', '2 Samuel'),
(11, 'pt', '1 Reis'),
(12, 'pt', '2 Reis'),
(13, 'pt', '1 Crônicas'),
(14, 'pt', '2 Crônicas'),
(15, 'pt', 'Esdras'),
(16, 'pt', 'Neemias'),
(17, 'pt', 'Ester'),
(18, 'pt', 'Jó'),
(19, 'pt', 'Salmos'),
(20, 'pt', 'Provérbios'),
(21, 'pt', 'Eclesiastes'),
(22, 'pt', 'Cânticos'),
(23, 'pt', 'Isaías'),
(24, 'pt', 'Jeremias'),
(25, 'pt', 'Lamentações'),
(26, 'pt', 'Ezequiel'),
(27, 'pt', 'Daniel'),
(28, 'pt', 'Oséias'),
(29, 'pt', 'Joel'),
(30, 'pt', 'Amós'),
(31, 'pt', 'Obadias'),
(32, 'pt', 'Jonas'),
(33, 'pt', 'Miquéias'),
(34, 'pt', 'Naum'),
(35, 'pt', 'Habacuque'),
(36, 'pt', 'Sofonias'),
(37, 'pt', 'Ageu'),
(38, 'pt', 'Zacarias'),
(39, 'pt', 'Malaquias'),
(40, 'pt', 'Mateus'),
(41, 'pt', 'Marcos'),
(42, 'pt', 'Lucas'),
(43, 'pt', 'João'),
(44, 'pt', 'Atos'),
(45, 'pt', 'Romanos'),
(46, 'pt', '1 Coríntios'),
(47, 'pt', '2 Coríntios'),
(48, 'pt', 'Gálatas'),
(49, 'pt', 'Efésios'),
(50, 'pt', 'Filipenses'),
(51, 'pt', 'Colossenses'),
(52, 'pt', '1 Tessalonicenses'),
(53, 'pt', '2 Tessalonicenses'),
(54, 'pt', '1 Timóteo'),
(55, 'pt', '2 Timóteo'),
(56, 'pt', 'Tito'),
(57, 'pt', 'Filemom'),
(58, 'pt', 'Hebreus'),
(59, 'pt', 'Tiago'),
(60, 'pt', '1 Pedro'),
(61, 'pt', '2 Pedro'),
(62, 'pt', '1 João'),
(63, 'pt', '2 João'),
(64, 'pt', '3 João'),
(65, 'pt', 'Judas'),
(66, 'pt', 'Apocalipse'),
(67, 'pt', 'Tobias'),
(68, 'pt', 'Judite'),
(69, 'pt', 'Sabedoria'),
(70, 'pt', 'Eclesiástico'),
(71, 'pt', 'Baruc'),
(72, 'pt', '1 Macabeus'),
(73, 'pt', '2 Macabeus'),

-- ===== Ukrainian (Українська) =====
(1,  'uk', 'Буття'),
(2,  'uk', 'Вихід'),
(3,  'uk', 'Левит'),
(4,  'uk', 'Числа'),
(5,  'uk', 'Повторення Закону'),
(6,  'uk', 'Ісус Навин'),
(7,  'uk', 'Книга Суддів'),
(8,  'uk', 'Рут'),
(9,  'uk', '1 Самуїла'),
(10, 'uk', '2 Самуїла'),
(11, 'uk', '1 Царів'),
(12, 'uk', '2 Царів'),
(13, 'uk', '1 Літопис'),
(14, 'uk', '2 Літопис'),
(15, 'uk', 'Ездра'),
(16, 'uk', 'Неемія'),
(17, 'uk', 'Естер'),
(18, 'uk', 'Йов'),
(19, 'uk', 'Псалми'),
(20, 'uk', 'Приповісті'),
(21, 'uk', 'Екклесіаст'),
(22, 'uk', 'Пісня Пісень'),
(23, 'uk', 'Ісая'),
(24, 'uk', 'Єремія'),
(25, 'uk', 'Плач Єремії'),
(26, 'uk', 'Езекіїл'),
(27, 'uk', 'Даниїл'),
(28, 'uk', 'Осіх'),
(29, 'uk', 'Йоель'),
(30, 'uk', 'Амос'),
(31, 'uk', 'Обдія'),
(32, 'uk', 'Йона'),
(33, 'uk', 'Михей'),
(34, 'uk', 'Наум'),
(35, 'uk', 'Аввакум'),
(36, 'uk', 'Софонія'),
(37, 'uk', 'Огій'),
(38, 'uk', 'Захарія'),
(39, 'uk', 'Малахії'),
(40, 'uk', 'Від Матвія'),
(41, 'uk', 'Від Марка'),
(42, 'uk', 'Від Луки'),
(43, 'uk', 'Від Івана'),
(44, 'uk', 'Дії Апостолів'),
(45, 'uk', 'До Римлян'),
(46, 'uk', '1 До Коринтян'),
(47, 'uk', '2 До Коринтян'),
(48, 'uk', 'До Галатів'),
(49, 'uk', 'До Ефесян'),
(50, 'uk', 'До Филипян'),
(51, 'uk', 'До Колосян'),
(52, 'uk', '1 До Солунян'),
(53, 'uk', '2 До Солунян'),
(54, 'uk', '1 До Тимофія'),
(55, 'uk', '2 До Тимофія'),
(56, 'uk', 'До Тита'),
(57, 'uk', 'До Филимона'),
(58, 'uk', 'До Євреїв'),
(59, 'uk', 'Якова'),
(60, 'uk', '1 Петра'),
(61, 'uk', '2 Петра'),
(62, 'uk', '1 Івана'),
(63, 'uk', '2 Івана'),
(64, 'uk', '3 Івана'),
(65, 'uk', 'Юди'),
(66, 'uk', 'Апокаліпсис'),
(67, 'uk', 'Товіт'),
(68, 'uk', 'Юдиф'),
(69, 'uk', 'Книга Мудрості'),
(70, 'uk', 'Сирах'),
(71, 'uk', 'Варух'),
(72, 'uk', '1 Маккавеїв'),
(73, 'uk', '2 Маккавеїв'),

-- ===== Vietnamese (Tiếng Việt) =====
(1,  'vi', 'Sáng Thế'),
(2,  'vi', 'Xuất Ai Cập'),
(3,  'vi', 'Lê Vi'),
(4,  'vi', 'Dân Số'),
(5,  'vi', 'Đệ Nhị Luật'),
(6,  'vi', 'Giô Suê'),
(7,  'vi', 'Các Quan Xét'),
(8,  'vi', 'Ru Tô'),
(9,  'vi', 'I Samuen'),
(10, 'vi', 'II Samuen'),
(11, 'vi', 'I Các Vua'),
(12, 'vi', 'II Các Vua'),
(13, 'vi', 'I Sử Ký'),
(14, 'vi', 'II Sử Ký'),
(15, 'vi', 'Epxra'),
(16, 'vi', 'Nêhemya'),
(17, 'vi', 'Êxtơ'),
(18, 'vi', 'Gióp'),
(19, 'vi', 'Thi Thiên'),
(20, 'vi', 'Châm Ngôn'),
(21, 'vi', 'Giáo Lý'),
(22, 'vi', 'Nhã Ca'),
(23, 'vi', 'I-sa-cha'),
(24, 'vi', 'Giê Rê Mi A'),
(25, 'vi', 'Ca Thương'),
(26, 'vi', 'E Xê Kien'),
(27, 'vi', 'Đa Niên'),
(28, 'vi', 'Hô Xê A'),
(29, 'vi', 'Gioên'),
(30, 'vi', 'A Mốt'),
(31, 'vi', 'Áp Đia'),
(32, 'vi', 'Giô Na'),
(33, 'vi', 'Mi Chi A'),
(34, 'vi', 'Na Hum'),
(35, 'vi', 'Ha Ba Cúc'),
(36, 'vi', 'Sô Phan Ia'),
(37, 'vi', 'A Gaghê'),
(38, 'vi', 'Da Ca Ri A'),
(39, 'vi', 'Ma La Chi A'),
(40, 'vi', 'Ma Thêu'),
(41, 'vi', 'Mác Cô'),
(42, 'vi', 'Lu Ca'),
(43, 'vi', 'Gioán'),
(44, 'vi', 'Công Vụ Tông Đồ'),
(45, 'vi', 'Rô Ma'),
(46, 'vi', 'I Cô Rin Tô'),
(47, 'vi', 'II Cô Rin Tô'),
(48, 'vi', 'Ga La Ti A'),
(49, 'vi', 'Ê Phê Sô'),
(50, 'vi', 'Phi Líp'),
(51, 'vi', 'Cô Lô Sê'),
(52, 'vi', 'I Tê Sa Lô Ni Ca'),
(53, 'vi', 'II Tê Sa Lô Ni Ca'),
(54, 'vi', 'I Ti Mô Thê'),
(55, 'vi', 'II Ti Mô Thê'),
(56, 'vi', 'Títô'),
(57, 'vi', 'Phi Lê Môn'),
(58, 'vi', 'Hê BỜ Rơ'),
(59, 'vi', 'Gia Cô'),
(60, 'vi', 'I Phierơ'),
(61, 'vi', 'II Phierơ'),
(62, 'vi', 'I Giôán'),
(63, 'vi', 'II Giôán'),
(64, 'vi', 'III Giôán'),
(65, 'vi', 'Giu Đa'),
(66, 'vi', 'Khải Huyền'),
(67, 'vi', 'Tô Bít'),
(68, 'vi', 'Giu Đít'),
(69, 'vi', 'Trí Huệ'),
(70, 'vi', 'Sí Rách'),
(71, 'vi', 'Ba Rút'),
(72, 'vi', 'I Ma Ca Bê'),
(73, 'vi', 'II Ma Ca Bê'),

-- ===== Japanese (日本語) =====
(1,  'ja', '創世記'),
(2,  'ja', '出エジプト記'),
(3,  'ja', 'レビ記'),
(4,  'ja', '民数記'),
(5,  'ja', '申命記'),
(6,  'ja', 'ヨシュア記'),
(7,  'ja', '士師記'),
(8,  'ja', 'ルツ記'),
(9,  'ja', 'サムエル記上'),
(10, 'ja', 'サムエル記下'),
(11, 'ja', '列王記上'),
(12, 'ja', '列王記下'),
(13, 'ja', '歴代志上'),
(14, 'ja', '歴代志下'),
(15, 'ja', 'エズラ記'),
(16, 'ja', 'ネヘミア記'),
(17, 'ja', 'エストエル記'),
(18, 'ja', 'ヨブ記'),
(19, 'ja', '詩篇'),
(20, 'ja', '箴言'),
(21, 'ja', '伝道の書'),
(22, 'ja', '雅歌'),
(23, 'ja', 'イザヤ書'),
(24, 'ja', 'エレミヤ書'),
(25, 'ja', '哀歌'),
(26, 'ja', 'エゼキエル書'),
(27, 'ja', 'ダニエル書'),
(28, 'ja', 'ホセア書'),
(29, 'ja', 'ヨエル書'),
(30, 'ja', 'アモス書'),
(31, 'ja', 'オバデア書'),
(32, 'ja', 'ヨナ書'),
(33, 'ja', 'ミカ書'),
(34, 'ja', 'ナホム書'),
(35, 'ja', 'ハバクク書'),
(36, 'ja', 'ゼパニヤ書'),
(37, 'ja', 'ハガイ書'),
(38, 'ja', 'ゼカリヤ書'),
(39, 'ja', 'マラキ書'),
(40, 'ja', 'マタイによる福音書'),
(41, 'ja', 'マルコによる福音書'),
(42, 'ja', 'ルカによる福音書'),
(43, 'ja', 'ヨハネによる福音書'),
(44, 'ja', '使徒言行録'),
(45, 'ja', 'ローマの信徒への手紙'),
(46, 'ja', 'コリントの信徒への手紙一'),
(47, 'ja', 'コリントの信徒への手紙二'),
(48, 'ja', 'ガラテヤの信徒への手紙'),
(49, 'ja', 'エフェソの信徒への手紙'),
(50, 'ja', 'ピリピの信徒への手紙'),
(51, 'ja', 'コロサイの信徒への手紙'),
(52, 'ja', 'テサロニケの信徒への手紙一'),
(53, 'ja', 'テサロニケの信徒への手紙二'),
(54, 'ja', 'テモテイへの手紙一'),
(55, 'ja', 'テモテイへの手紙二'),
(56, 'ja', 'テトスへの手紙'),
(57, 'ja', 'ピレモンへの手紙'),
(58, 'ja', 'ヘブライ人への手紙'),
(59, 'ja', 'ヤコブの手紙'),
(60, 'ja', 'ペトロの手紙一'),
(61, 'ja', 'ペトロの手紙二'),
(62, 'ja', 'ヨハネの手紙一'),
(63, 'ja', 'ヨハネの手紙二'),
(64, 'ja', 'ヨハネの手紙三'),
(65, 'ja', 'ユダの手紙'),
(66, 'ja', 'ヨハネの黙示録'),
(67, 'ja', 'トビト記'),
(68, 'ja', 'ユディト記'),
(69, 'ja', '知恵の書'),
(70, 'ja', 'シラ書'),
(71, 'ja', 'バルク書'),
(72, 'ja', 'マカベオ記一'),
(73, 'ja', 'マカベオ記二'),

-- ===== Korean (한국어) =====
(1,  'ko', '창세기'),
(2,  'ko', '출애굽기'),
(3,  'ko', '레위기'),
(4,  'ko', '민수기'),
(5,  'ko', '신명기'),
(6,  'ko', '여호수아기'),
(7,  'ko', '사사기'),
(8,  'ko', '룻기'),
(9,  'ko', '사무엘상'),
(10, 'ko', '사무엘하'),
(11, 'ko', '열왕기상'),
(12, 'ko', '열왕기하'),
(13, 'ko', '역대상'),
(14, 'ko', '역대하'),
(15, 'ko', '에스라기'),
(16, 'ko', '느헤미야기'),
(17, 'ko', '에스더기'),
(18, 'ko', '욥기'),
(19, 'ko', '시편'),
(20, 'ko', '잠언'),
(21, 'ko', '전도서'),
(22, 'ko', '아가'),
(23, 'ko', '이사야서'),
(24, 'ko', '예레미야서'),
(25, 'ko', '예레미야애가'),
(26, 'ko', '에스겔서'),
(27, 'ko', '다니엘서'),
(28, 'ko', '호세아서'),
(29, 'ko', '요엘서'),
(30, 'ko', '아모스서'),
(31, 'ko', '오바댜서'),
(32, 'ko', '요나서'),
(33, 'ko', '미가서'),
(34, 'ko', '나훔서'),
(35, 'ko', '하박국서'),
(36, 'ko', '스바냐서'),
(37, 'ko', '학개서'),
(38, 'ko', '사가랴서'),
(39, 'ko', '말라기서'),
(40, 'ko', '마태오복음서'),
(41, 'ko', '마르코복음서'),
(42, 'ko', '누가복음서'),
(43, 'ko', '요한복음서'),
(44, 'ko', '사도행전'),
(45, 'ko', '로마서'),
(46, 'ko', '고린도전서'),
(47, 'ko', '고린도후서'),
(48, 'ko', '갈라디아서'),
(49, 'ko', '에베소서'),
(50, 'ko', '빌립보서'),
(51, 'ko', '골로새서'),
(52, 'ko', '데살로니가전서'),
(53, 'ko', '데살로니가후서'),
(54, 'ko', '디모데전서'),
(55, 'ko', '디모데후서'),
(56, 'ko', '디도서'),
(57, 'ko', '빌레몬서'),
(58, 'ko', '히브리서'),
(59, 'ko', '야고보서'),
(60, 'ko', '베드로전서'),
(61, 'ko', '베드로후서'),
(62, 'ko', '요한일서'),
(63, 'ko', '요한이서'),
(64, 'ko', '요한삼서'),
(65, 'ko', '유다서'),
(66, 'ko', '요한계시록'),
(67, 'ko', '토빗기'),
(68, 'ko', '유dit서'),
(69, 'ko', '지혜서'),
(70, 'ko', '집회서'),
(71, 'ko', '바룩서'),
(72, 'ko', '마카베오기'),
(73, 'ko', '마카베오'),

-- ===== Chinese Simplified (简体中文) =====
(1,  'zh', '创世记'),
(2,  'zh', '出埃及记'),
(3,  'zh', '利未记'),
(4,  'zh', '民数记'),
(5,  'zh', '申命记'),
(6,  'zh', '约书亚记'),
(7,  'zh', '士师记'),
(8,  'zh', '路得记'),
(9,  'zh', '撒母耳记上'),
(10, 'zh', '撒母耳记下'),
(11, 'zh', '列王纪上'),
(12, 'zh', '列王纪下'),
(13, 'zh', '历代志上'),
(14, 'zh', '历代志下'),
(15, 'zh', '以斯拉记'),
(16, 'zh', '尼希米记'),
(17, 'zh', '以斯帖记'),
(18, 'zh', '约伯记'),
(19, 'zh', '诗篇'),
(20, 'zh', '箴言'),
(21, 'zh', '传道书'),
(22, 'zh', '雅歌'),
(23, 'zh', '以赛亚书'),
(24, 'zh', '耶利米书'),
(25, 'zh', '耶利米哀歌'),
(26, 'zh', '以西结书'),
(27, 'zh', '但以理书'),
(28, 'zh', '何西阿书'),
(29, 'zh', '约珥书'),
(30, 'zh', '阿摩司书'),
(31, 'zh', '俄巴底亚书'),
(32, 'zh', '约拿书'),
(33, 'zh', '弥迦书'),
(34, 'zh', '那鸿书'),
(35, 'zh', '哈巴谷书'),
(36, 'zh', '西番雅书'),
(37, 'zh', '哈该书'),
(38, 'zh', '撒迦利亚书'),
(39, 'zh', '玛拉基书'),
(40, 'zh', '马太福音'),
(41, 'zh', '马可福音'),
(42, 'zh', '路加福音'),
(43, 'zh', '约翰福音'),
(44, 'zh', '使徒行传'),
(45, 'zh', '罗马书'),
(46, 'zh', '哥林多前书'),
(47, 'zh', '哥林多后书'),
(48, 'zh', '加拉太书'),
(49, 'zh', '以弗所书'),
(50, 'zh', '腓立比书'),
(51, 'zh', '歌罗西书'),
(52, 'zh', '帖撒罗尼迦前书'),
(53, 'zh', '帖撒罗尼迦后书'),
(54, 'zh', '提摩太前书'),
(55, 'zh', '提摩太后书'),
(56, 'zh', '提多书'),
(57, 'zh', '腓利门书'),
(58, 'zh', '希伯来书'),
(59, 'zh', '雅各书'),
(60, 'zh', '彼得前书'),
(61, 'zh', '彼得后书'),
(62, 'zh', '约翰一书'),
(63, 'zh', '约翰二书'),
(64, 'zh', '约翰三书'),
(65, 'zh', '犹大书'),
(66, 'zh', '启示录'),
(67, 'zh', '多比传'),
(68, 'zh', '犹滴传'),
(69, 'zh', '智慧篇'),
(70, 'zh', '德训篇'),
(71, 'zh', '巴路克书'),
(72, 'zh', '玛加伯书上'),
(73, 'zh', '玛加伯书下');

-- Note: verse data is imported separately using the osis_to_sql CLI tool.
-- Example:
--   python -m scriptura.osis_to_sql --osis vulgata.xml --books osis_books.toml --output verses.sql
--   psql -h HOST -U USER DBNAME -c "COPY verses FROM STDIN (FORMAT csv, HEADER true);" < verses.csv
-- or simply:
--   psql -h HOST -U USER DBNAME -f verses.sql
